// source: https://www.artlebedev.ru/country-list/

export interface ICountry {
  name: string;
  label_en: string;
  code: string;
  iso: string;
}

export const fullListOfCountries = [
  { name: 'Абхазия', label_en: 'Abkhazia', code: 'AB', iso: '895' },
  { name: 'Австралия', label_en: 'Australia', code: 'AU', iso: '036' },
  { name: 'Австрия', label_en: 'Austria', code: 'AT', iso: '040' },
  { name: 'Азербайджан', label_en: 'Azerbaijan', code: 'AZ', iso: '031' },
  { name: 'Албания', label_en: 'Albania', code: 'AL', iso: '008' },
  { name: 'Алжир', label_en: 'Algeria', code: 'DZ', iso: '012' },
  { name: 'Американское Самоа', label_en: 'American Samoa', code: 'AS', iso: '016' },
  { name: 'Ангилья', label_en: 'Anguilla', code: 'AI', iso: '660' },
  { name: 'Ангола', label_en: 'Angola', code: 'AO', iso: '024' },
  { name: 'Андорра', label_en: 'Andorra', code: 'AD', iso: '020' },
  { name: 'Антарктида', label_en: 'Antarctica', code: 'AQ', iso: '010' },
  { name: 'Антигуа и Барбуда', label_en: 'Antigua and Barbuda', code: 'AG', iso: '028' },
  { name: 'Аргентина', label_en: 'Argentina', code: 'AR', iso: '032' },
  { name: 'Армения', label_en: 'Armenia', code: 'AM', iso: '051' },
  { name: 'Аруба', label_en: 'Aruba', code: 'AW', iso: '533' },
  { name: 'Афганистан', label_en: 'Afghanistan', code: 'AF', iso: '004' },
  { name: 'Багамы', label_en: 'Bahamas', code: 'BS', iso: '044' },
  { name: 'Бангладеш', label_en: 'Bangladesh', code: 'BD', iso: '050' },
  { name: 'Барбадос', label_en: 'Barbados', code: 'BB', iso: '052' },
  { name: 'Бахрейн', label_en: 'Bahrain', code: 'BH', iso: '048' },
  { name: 'Беларусь', label_en: 'Belarus', code: 'BY', iso: '112' },
  { name: 'Белиз', label_en: 'Belize', code: 'BZ', iso: '084' },
  { name: 'Бельгия', label_en: 'Belgium', code: 'BE', iso: '056' },
  { name: 'Бенин', label_en: 'Benin', code: 'BJ', iso: '204' },
  { name: 'Бермуды', label_en: 'Bermuda', code: 'BM', iso: '060' },
  { name: 'Болгария', label_en: 'Bulgaria', code: 'BG', iso: '100' },
  { name: 'Боливия', label_en: 'Bolivia', code: 'BO', iso: '068' },
  { name: 'Бонайре, Саба и Синт-Эстатиус', label_en: 'Bonaire, Sint Eustatius and Saba', code: 'BQ', iso: '535' },
  { name: 'Босния и Герцеговина', label_en: 'Bosnia and Herzegovina', code: 'BA', iso: '070' },
  { name: 'Ботсвана', label_en: 'Botswana', code: 'BW', iso: '072' },
  { name: 'Бразилия', label_en: 'Brazil', code: 'BR', iso: '076' },
  { name: 'Британская территория в Индийском океане', label_en: 'British Indian Ocean Territory', code: 'IO', iso: '086' },
  { name: 'Бруней-Даруссалам', label_en: 'Brunei Darussalam', code: 'BN', iso: '096' },
  { name: 'Буркина-Фасо', label_en: 'Burkina Faso', code: 'BF', iso: '854' },
  { name: 'Бурунди', label_en: 'Burundi', code: 'BI', iso: '108' },
  { name: 'Бутан', label_en: 'Bhutan', code: 'BT', iso: '064' },
  { name: 'Вануату', label_en: 'Vanuatu', code: 'VU', iso: '548' },
  { name: 'Венгрия', label_en: 'Hungary', code: 'HU', iso: '348' },
  { name: 'Венесуэла', label_en: 'Venezuela', code: 'VE', iso: '862' },
  { name: 'Виргинские острова, Британские', label_en: 'Virgin Islands, British', code: 'VG', iso: '092' },
  { name: 'Виргинские острова, США', label_en: 'Virgin Islands, U.S.', code: 'VI', iso: '850' },
  { name: 'Вьетнам', label_en: 'Vietnam', code: 'VN', iso: '704' },
  { name: 'Габон', label_en: 'Gabon', code: 'GA', iso: '266' },
  { name: 'Гаити', label_en: 'Haiti', code: 'HT', iso: '332' },
  { name: 'Гайана', label_en: 'Guyana', code: 'GY', iso: '328' },
  { name: 'Гамбия', label_en: 'Gambia', code: 'GM', iso: '270' },
  { name: 'Гана', label_en: 'Ghana', code: 'GH', iso: '288' },
  { name: 'Гваделупа', label_en: 'Guadeloupe', code: 'GP', iso: '312' },
  { name: 'Гватемала', label_en: 'Guatemala', code: 'GT', iso: '320' },
  { name: 'Гвинея', label_en: 'Guinea', code: 'GN', iso: '324' },
  { name: 'Гвинея-Бисау', label_en: 'Guinea-Bissau', code: 'GW', iso: '624' },
  { name: 'Германия', label_en: 'Germany', code: 'DE', iso: '276' },
  { name: 'Гернси', label_en: 'Guernsey', code: 'GG', iso: '831' },
  { name: 'Гибралтар', label_en: 'Gibraltar', code: 'GI', iso: '292' },
  { name: 'Гондурас', label_en: 'Honduras', code: 'HN', iso: '340' },
  { name: 'Гонконг', label_en: 'Hong Kong', code: 'HK', iso: '344' },
  { name: 'Гренада', label_en: 'Grenada', code: 'GD', iso: '308' },
  { name: 'Гренландия', label_en: 'Greenland', code: 'GL', iso: '304' },
  { name: 'Греция', label_en: 'Greece', code: 'GR', iso: '300' },
  { name: 'Грузия', label_en: 'Georgia', code: 'GE', iso: '268' },
  { name: 'Гуам', label_en: 'Guam', code: 'GU', iso: '316' },
  { name: 'Дания', label_en: 'Denmark', code: 'DK', iso: '208' },
  { name: 'Джерси', label_en: 'Jersey', code: 'JE', iso: '832' },
  { name: 'Джибути', label_en: 'Djibouti', code: 'DJ', iso: '262' },
  { name: 'Доминика', label_en: 'Dominica', code: 'DM', iso: '212' },
  { name: 'Доминиканская Республика', label_en: 'Dominican Republic', code: 'DO', iso: '214' },
  { name: 'Египет', label_en: 'Egypt', code: 'EG', iso: '818' },
  { name: 'Замбия', label_en: 'Zambia', code: 'ZM', iso: '894' },
  { name: 'Западная Сахара', label_en: 'Western Sahara', code: 'EH', iso: '732' },
  { name: 'Зимбабве', label_en: 'Zimbabwe', code: 'ZW', iso: '716' },
  { name: 'Израиль', label_en: 'Israel', code: 'IL', iso: '376' },
  { name: 'Индия', label_en: 'India', code: 'IN', iso: '356' },
  { name: 'Индонезия', label_en: 'Indonesia', code: 'ID', iso: '360' },
  { name: 'Иордания', label_en: 'Jordan', code: 'JO', iso: '400' },
  { name: 'Ирак', label_en: 'Iraq', code: 'IQ', iso: '368' },
  { name: 'Иран', label_en: 'Iran', code: 'IR', iso: '364' },
  { name: 'Ирландия', label_en: 'Ireland', code: 'IE', iso: '372' },
  { name: 'Исландия', label_en: 'Iceland', code: 'IS', iso: '352' },
  { name: 'Испания', label_en: 'Spain', code: 'ES', iso: '724' },
  { name: 'Италия', label_en: 'Italy', code: 'IT', iso: '380' },
  { name: 'Йемен', label_en: 'Yemen', code: 'YE', iso: '887' },
  { name: 'Кабо-Верде', label_en: 'Cape Verde', code: 'CV', iso: '132' },
  { name: 'Казахстан', label_en: 'Kazakhstan', code: 'KZ', iso: '398' },
  { name: 'Камбоджа', label_en: 'Cambodia', code: 'KH', iso: '116' },
  { name: 'Камерун', label_en: 'Cameroon', code: 'CM', iso: '120' },
  { name: 'Канада', label_en: 'Canada', code: 'CA', iso: '124' },
  { name: 'Катар', label_en: 'Qatar', code: 'QA', iso: '634' },
  { name: 'Кения', label_en: 'Kenya', code: 'KE', iso: '404' },
  { name: 'Кипр', label_en: 'Cyprus', code: 'CY', iso: '196' },
  { name: 'Киргизия', label_en: 'Kyrgyzstan', code: 'KG', iso: '417' },
  { name: 'Кирибати', label_en: 'Kiribati', code: 'KI', iso: '296' },
  { name: 'Китай', label_en: 'China', code: 'CN', iso: '156' },
  { name: 'Кокосовые (Килинг) острова', label_en: 'Cocos (Keeling) Islands', code: 'CC', iso: '166' },
  { name: 'Колумбия', label_en: 'Colombia', code: 'CO', iso: '170' },
  { name: 'Коморы', label_en: 'Comoros', code: 'KM', iso: '174' },
  { name: 'Конго', label_en: 'Congo', code: 'CG', iso: '178' },
  { name: 'Конго', label_en: 'Congo, Democratic Republic of the', code: 'CD', iso: '180' },
  { name: 'КНДР', label_en: 'DPRK', code: 'KP', iso: '408' },
  { name: 'Южная Корея', label_en: 'Southern Korea', code: 'KR', iso: '410' },
  { name: 'Коста-Рика', label_en: 'Costa Rica', code: 'CR', iso: '188' },
  { name: 'Кот д`Ивуар', label_en: 'Cote d`Ivoire', code: 'CI', iso: '384' },
  { name: 'Куба', label_en: 'Cuba', code: 'CU', iso: '192' },
  { name: 'Кувейт', label_en: 'Kuwait', code: 'KW', iso: '414' },
  { name: 'Кюрасао', label_en: 'Curaçao', code: 'CW', iso: '531' },
  { name: 'Лаос', label_en: 'Laos', code: 'LA', iso: '418' },
  { name: 'Латвия', label_en: 'Latvia', code: 'LV', iso: '428' },
  { name: 'Лесото', label_en: 'Lesotho', code: 'LS', iso: '426' },
  { name: 'Ливан', label_en: 'Lebanon', code: 'LB', iso: '422' },
  { name: 'Ливия', label_en: 'Libya', code: 'LY', iso: '434' },
  { name: 'Либерия', label_en: 'Liberia', code: 'LR', iso: '430' },
  { name: 'Лихтенштейн', label_en: 'Liechtenstein', code: 'LI', iso: '438' },
  { name: 'Литва', label_en: 'Lithuania', code: 'LT', iso: '440' },
  { name: 'Люксембург', label_en: 'Luxembourg', code: 'LU', iso: '442' },
  { name: 'Маврикий', label_en: 'Mauritius', code: 'MU', iso: '480' },
  { name: 'Мавритания', label_en: 'Mauritania', code: 'MR', iso: '478' },
  { name: 'Мадагаскар', label_en: 'Madagascar', code: 'MG', iso: '450' },
  { name: 'Майотта', label_en: 'Mayotte', code: 'YT', iso: '175' },
  { name: 'Макао', label_en: 'Macao', code: 'MO', iso: '446' },
  { name: 'Малави', label_en: 'Malawi', code: 'MW', iso: '454' },
  { name: 'Малайзия', label_en: 'Malaysia', code: 'MY', iso: '458' },
  { name: 'Мали', label_en: 'Mali', code: 'ML', iso: '466' },
  { name: 'Малые Тихоокеанские отдаленные острова Соединенных Штатов', label_en: 'United States Minor Outlying Islands', code: 'UM', iso: '581' },
  { name: 'Мальдивы', label_en: 'Maldives', code: 'MV', iso: '462' },
  { name: 'Мальта', label_en: 'Malta', code: 'MT', iso: '470' },
  { name: 'Марокко', label_en: 'Morocco', code: 'MA', iso: '504' },
  { name: 'Мартиника', label_en: 'Martinique', code: 'MQ', iso: '474' },
  { name: 'Маршалловы острова', label_en: 'Marshall Islands', code: 'MH', iso: '584' },
  { name: 'Мексика', label_en: 'Mexico', code: 'MX', iso: '484' },
  { name: 'Микронезия', label_en: 'Micronesia', code: 'FM', iso: '583' },
  { name: 'Мозамбик', label_en: 'Mozambique', code: 'MZ', iso: '508' },
  { name: 'Молдова, Республика', label_en: 'Moldova', code: 'MD', iso: '498' },
  { name: 'Монако', label_en: 'Monaco', code: 'MC', iso: '492' },
  { name: 'Монголия', label_en: 'Mongolia', code: 'MN', iso: '496' },
  { name: 'Монтсеррат', label_en: 'Montserrat', code: 'MS', iso: '500' },
  { name: 'Мьянма', label_en: 'Myanmar', code: 'MM', iso: '104' },
  { name: 'Намибия', label_en: 'Namibia', code: 'NA', iso: '516' },
  { name: 'Науру', label_en: 'Nauru', code: 'NR', iso: '520' },
  { name: 'Непал', label_en: 'Nepal', code: 'NP', iso: '524' },
  { name: 'Нигер', label_en: 'Niger', code: 'NE', iso: '562' },
  { name: 'Нигерия', label_en: 'Nigeria', code: 'NG', iso: '566' },
  { name: 'Нидерланды', label_en: 'Netherlands', code: 'NL', iso: '528' },
  { name: 'Никарагуа', label_en: 'Nicaragua', code: 'NI', iso: '558' },
  { name: 'Ниуэ', label_en: 'Niue', code: 'NU', iso: '570' },
  { name: 'Новая Зеландия', label_en: 'New Zealand', code: 'NZ', iso: '554' },
  { name: 'Новая Каледония', label_en: 'New Caledonia', code: 'NC', iso: '540' },
  { name: 'Норвегия', label_en: 'Norway', code: 'NO', iso: '578' },
  { name: 'ОАЭ', label_en: 'UAE', code: 'AE', iso: '784' },
  { name: 'Оман', label_en: 'Oman', code: 'OM', iso: '512' },
  { name: 'Остров Буве', label_en: 'Bouvet Island', code: 'BV', iso: '074' },
  { name: 'Остров Мэн', label_en: 'Isle of Man', code: 'IM', iso: '833' },
  { name: 'Остров Норфолк', label_en: 'Norfolk Island', code: 'NF', iso: '574' },
  { name: 'Остров Рождества', label_en: 'Christmas Island', code: 'CX', iso: '162' },
  { name: 'Остров Херд и острова Макдональд', label_en: 'Heard Island and McDonald Islands', code: 'HM', iso: '334' },
  { name: 'Острова Кайман', label_en: 'Cayman Islands', code: 'KY', iso: '136' },
  { name: 'Острова Кука', label_en: 'Cook Islands', code: 'CK', iso: '184' },
  { name: 'Острова Теркс и Кайкос', label_en: 'Turks and Caicos Islands', code: 'TC', iso: '796' },
  { name: 'Пакистан', label_en: 'Pakistan', code: 'PK', iso: '586' },
  { name: 'Палау', label_en: 'Palau', code: 'PW', iso: '585' },
  { name: 'Палестинская территория', label_en: 'Palestinian Territory', code: 'PS', iso: '275' },
  { name: 'Панама', label_en: 'Panama', code: 'PA', iso: '591' },
  { name: 'Ватикан', label_en: 'Vatican', code: 'VA', iso: '336' },
  { name: 'Папуа-Новая Гвинея', label_en: 'Papua New Guinea', code: 'PG', iso: '598' },
  { name: 'Парагвай', label_en: 'Paraguay', code: 'PY', iso: '600' },
  { name: 'Перу', label_en: 'Peru', code: 'PE', iso: '604' },
  { name: 'Питкерн', label_en: 'Pitcairn', code: 'PN', iso: '612' },
  { name: 'Польша', label_en: 'Poland', code: 'PL', iso: '616' },
  { name: 'Португалия', label_en: 'Portugal', code: 'PT', iso: '620' },
  { name: 'Пуэрто-Рико', label_en: 'Puerto Rico', code: 'PR', iso: '630' },
  { name: 'Республика Македония', label_en: 'Macedonia, The Former Yugoslav Republic Of', code: 'MK', iso: '807' },
  { name: 'Реюньон', label_en: 'Reunion', code: 'RE', iso: '638' },
  { name: 'Россия', label_en: 'Russian Federation', code: 'RU', iso: '643' },
  { name: 'Руанда', label_en: 'Rwanda', code: 'RW', iso: '646' },
  { name: 'Румыния', label_en: 'Romania', code: 'RO', iso: '642' },
  { name: 'Самоа', label_en: 'Samoa', code: 'WS', iso: '882' },
  { name: 'Сан-Марино', label_en: 'San Marino', code: 'SM', iso: '674' },
  { name: 'Сан-Томе и Принсипи', label_en: 'Sao Tome and Principe', code: 'ST', iso: '678' },
  { name: 'Саудовская Аравия', label_en: 'Saudi Arabia', code: 'SA', iso: '682' },
  { name: 'Свазиленд', label_en: 'Swaziland', code: 'SZ', iso: '748' },
  { name: 'Святая Елена, Остров вознесения, Тристан-да-Кунья', label_en: 'Saint Helena, Ascension And Tristan Da Cunha', code: 'SH', iso: '654' },
  { name: 'Северные Марианские острова', label_en: 'Northern Mariana Islands', code: 'MP', iso: '580' },
  { name: 'Сен-Бартельми', label_en: 'Saint Barthélemy', code: 'BL', iso: '652' },
  { name: 'Сен-Мартен', label_en: 'Saint Martin (French Part)', code: 'MF', iso: '663' },
  { name: 'Сенегал', label_en: 'Senegal', code: 'SN', iso: '686' },
  { name: 'Сент-Винсент и Гренадины', label_en: 'Saint Vincent and the Grenadines', code: 'VC', iso: '670' },
  { name: 'Сент-Люсия', label_en: 'Saint Lucia', code: 'LC', iso: '662' },
  { name: 'Сент-Китс и Невис', label_en: 'Saint Kitts and Nevis', code: 'KN', iso: '659' },
  { name: 'Сент-Пьер и Микелон', label_en: 'Saint Pierre and Miquelon', code: 'PM', iso: '666' },
  { name: 'Сербия', label_en: 'Serbia', code: 'RS', iso: '688' },
  { name: 'Сейшелы', label_en: 'Seychelles', code: 'SC', iso: '690' },
  { name: 'Сингапур', label_en: 'Singapore', code: 'SG', iso: '702' },
  { name: 'Синт-Мартен', label_en: 'Sint Maarten', code: 'SX', iso: '534' },
  { name: 'Сирийская Арабская Республика', label_en: 'Syrian Arab Republic', code: 'SY', iso: '760' },
  { name: 'Словакия', label_en: 'Slovakia', code: 'SK', iso: '703' },
  { name: 'Словения', label_en: 'Slovenia', code: 'SI', iso: '705' },
  { name: 'Соединенное Королевство', label_en: 'United Kingdom', code: 'GB', iso: '826' },
  { name: 'Соединенные Штаты', label_en: 'United States', code: 'US', iso: '840' },
  { name: 'Соломоновы острова', label_en: 'Solomon Islands', code: 'SB', iso: '090' },
  { name: 'Сомали', label_en: 'Somalia', code: 'SO', iso: '706' },
  { name: 'Судан', label_en: 'Sudan', code: 'SD', iso: '729' },
  { name: 'Суринам', label_en: 'Suriname', code: 'SR', iso: '740' },
  { name: 'Сьерра-Леоне', label_en: 'Sierra Leone', code: 'SL', iso: '694' },
  { name: 'Таджикистан', label_en: 'Tajikistan', code: 'TJ', iso: '762' },
  { name: 'Таиланд', label_en: 'Thailand', code: 'TH', iso: '764' },
  { name: 'Тайвань (Китай)', label_en: 'Taiwan, Province of China', code: 'TW', iso: '158' },
  { name: 'Танзания, Объединенная Республика', label_en: 'Tanzania, United Republic Of', code: 'TZ', iso: '834' },
  { name: 'Тимор-Лесте', label_en: 'Timor-Leste', code: 'TL', iso: '626' },
  { name: 'Того', label_en: 'Togo', code: 'TG', iso: '768' },
  { name: 'Токелау', label_en: 'Tokelau', code: 'TK', iso: '772' },
  { name: 'Тонга', label_en: 'Tonga', code: 'TO', iso: '776' },
  { name: 'Тринидад и Тобаго', label_en: 'Trinidad and Tobago', code: 'TT', iso: '780' },
  { name: 'Тувалу', label_en: 'Tuvalu', code: 'TV', iso: '798' },
  { name: 'Тунис', label_en: 'Tunisia', code: 'TN', iso: '788' },
  { name: 'Туркмения', label_en: 'Turkmenistan', code: 'TM', iso: '795' },
  { name: 'Турция', label_en: 'Turkey', code: 'TR', iso: '792' },
  { name: 'Уганда', label_en: 'Uganda', code: 'UG', iso: '800' },
  { name: 'Узбекистан', label_en: 'Uzbekistan', code: 'UZ', iso: '860' },
  { name: 'Украина', label_en: 'Ukraine', code: 'UA', iso: '804' },
  { name: 'Уоллис и Футуна', label_en: 'Wallis and Futuna', code: 'WF', iso: '876' },
  { name: 'Уругвай', label_en: 'Uruguay', code: 'UY', iso: '858' },
  { name: 'Фарерские острова', label_en: 'Faroe Islands', code: 'FO', iso: '234' },
  { name: 'Фиджи', label_en: 'Fiji', code: 'FJ', iso: '242' },
  { name: 'Филиппины', label_en: 'Philippines', code: 'PH', iso: '608' },
  { name: 'Финляндия', label_en: 'Finland', code: 'FI', iso: '246' },
  { name: 'Фолклендские острова (Мальвинские)', label_en: 'Falkland Islands (Malvinas)', code: 'FK', iso: '238' },
  { name: 'Франция', label_en: 'France', code: 'FR', iso: '250' },
  { name: 'Французская Гвиана', label_en: 'French Guiana', code: 'GF', iso: '254' },
  { name: 'Французская Полинезия', label_en: 'French Polynesia', code: 'PF', iso: '258' },
  { name: 'Французские Южные территории', label_en: 'French Southern Territories', code: 'TF', iso: '260' },
  { name: 'Хорватия', label_en: 'Croatia', code: 'HR', iso: '191' },
  { name: 'Центрально-Африканская Республика', label_en: 'Central African Republic', code: 'CF', iso: '140' },
  { name: 'Чад', label_en: 'Chad', code: 'TD', iso: '148' },
  { name: 'Черногория', label_en: 'Montenegro', code: 'ME', iso: '499' },
  { name: 'Чешская Республика', label_en: 'Czech Republic', code: 'CZ', iso: '203' },
  { name: 'Чили', label_en: 'Chile', code: 'CL', iso: '152' },
  { name: 'Швейцария', label_en: 'Switzerland', code: 'CH', iso: '756' },
  { name: 'Швеция', label_en: 'Sweden', code: 'SE', iso: '752' },
  { name: 'Шпицберген и Ян Майен', label_en: 'Svalbard and Jan Mayen', code: 'SJ', iso: '744' },
  { name: 'Шри-Ланка', label_en: 'Sri Lanka', code: 'LK', iso: '144' },
  { name: 'Эквадор', label_en: 'Ecuador', code: 'EC', iso: '218' },
  { name: 'Экваториальная Гвинея', label_en: 'Equatorial Guinea', code: 'GQ', iso: '226' },
  { name: 'Эландские острова', label_en: 'Åland Islands', code: 'AX', iso: '248' },
  { name: 'Эль-Сальвадор', label_en: 'El Salvador', code: 'SV', iso: '222' },
  { name: 'Эритрея', label_en: 'Eritrea', code: 'ER', iso: '232' },
  { name: 'Эстония', label_en: 'Estonia', code: 'EE', iso: '233' },
  { name: 'Эфиопия', label_en: 'Ethiopia', code: 'ET', iso: '231' },
  { name: 'Южная Африка', label_en: 'South Africa', code: 'ZA', iso: '710' },
  { name: 'Южная Джорджия', label_en: 'South Georgia', code: 'GS', iso: '239' },
  { name: 'Южная Осетия', label_en: 'South Ossetia', code: 'OS', iso: '896' },
  { name: 'Южный Судан', label_en: 'South Sudan', code: 'SS', iso: '728' },
  { name: 'Ямайка', label_en: 'Jamaica', code: 'JM', iso: '388' },
  { name: 'Япония', label_en: 'Japan', code: 'JP', iso: '392' },
];
